DESCRIPTION = "IoTConnect Python Lite SDK"
HOMEPAGE = "https://github.com/avnet-iotconnect/iotc-python-lite-sdk"
LICENSE = "CLOSED"
SRC_URI = "git://github.com/avnet-iotconnect/iotc-python-lite-sdk.git;branch=main"
SRCREV = "f0b5bf006b716d2de361e3df8b94f684f9872497>"
PV = "1.0.0+git${SRCPV}"
PR = "r0"
S = "${WORKDIR}/git"
inherit setuptools3
RDEPENDS:${PN} = "python3 python3-toml"
